### ISSUE TITLE
Vendor Class Option seems not correct

### ISSUE THREAD

**Issue by jerome-laforge** [mdlayher/dhcp6#10]
Hello,
OptionVendorClass seems not respect RFC  3315, Section 22.16.
Cause the EnterpriseNumber is missing.

I have fix, plz see at:
https://github.com/jerome-laforge/dhcp6/commit/78927a18b545211ced8c2e832aadc36ae6ded11e

If it suitable for you, I can make PR.
thx

**Comment by mdlayher** [comment]
Yep, makes sense to me.  Feel free to send a PR.

**Comment by jerome-laforge** [comment]
thx
