### ISSUE TITLE
Set slice's max for option's data

### ISSUE THREAD

**Issue by jerome-laforge** [mdlayher/dhcp6#13]
Hello,
In unit test of our internal injector, we use to compare expected [DHCPv6 packet](https://godoc.org/github.com/mdlayher/dhcp6#Packet) and actual packet with [this assert](https://godoc.org/github.com/dvln/testify/assert#EqualValues).

Unfortunately, on the capacity option is not equal when when unmarshall from binary and when we create the packet from struct because capacity is not the same. So assert fails.

Here example's extract:
```diff
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(*dhcp6.Packet)(0xc82001b640)({
+(*dhcp6.Packet)(0xc82001b650)({
  MessageType: (dhcp6.MessageType) MessageTypeSolicit,
@@ -7,3 +7,3 @@
   (dhcp6.OptionCode) OptionClientID: ([][]uint8) (len=1 cap=1) {
-   ([]uint8) (len=10 cap=130) {
+   ([]uint8) (len=10 cap=10) {
```

By the way, I seems to me more consistent, that set slice's max for option's data for avoiding all corrupt data (for example with append)
This commit is fixing this pb:
https://github.com/jerome-laforge/dhcp6/commit/2ba8cd69e42c7988facede487423eeccb703137a

If it is suitable for you, I can make a PR.

**Comment by mdlayher** [comment]
Yep, seems reasonable to me.  Please submit a PR.
