### ISSUE TITLE
InterfaceID doesn't respect RFC 3315

### ISSUE THREAD

**Issue by jerome-laforge** [mdlayher/dhcp6#14]
Hello
InterfaceID seem not respect the RFC 3315.
InterfaceID is just opaque value and not Length-Value.

Plz see this commit that fix this issue:
https://github.com/jerome-laforge/dhcp6/commit/113a6bf6a8e1999dee63e32d363ffa687b36111c

**Comment by mdlayher** [comment]
Seems reasonable to me.  Submit a PR please.
