### ISSUE TITLE
ElapsedTime when elapsed time values greater than the largest time value that can be represented in the Elapsed Time option.

### ISSUE THREAD

**Issue by jerome-laforge** [mdlayher/dhcp6#19]
Hello,
When elapsed time values greater than the largest time value that can be represented in the Elapsed Time option, the client uses the value 0xffff.

Plz this commit
https://github.com/jerome-laforge/dhcp6/commit/924665b1b681f36187f78da14256467fc0fd8fa2

If it is suitable for you, I can submit a PR

**Comment by mdlayher** [comment]
Looks good! Please do submit a PR.
